version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - MYSQL_DATABASE=lite_exchange
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=lite_exchange
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"

volumes:
  mysql_data:
