# Generated by Django 5.0.3 on 2024-05-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sellerprofile_bio_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
