# Generated by Django 5.0.3 on 2024-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sellerprofile_hourly_rate_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date_awarded',
            field=models.DateField(help_text='2024-05-18'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='2000-05-18', null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(help_text='2021-05-18'),
        ),
    ]
