# Generated by Django 5.0.3 on 2024-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Freelance', 'Freelance'), ('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship')], default='Full time', max_length=15),
        ),
    ]
