# Generated by Django 5.0.3 on 2024-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
