# Generated by Django 5.0.3 on 2024-06-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_job_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Jobs_images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='set the end date of the applications', null=True),
        ),
    ]
